<?php // article/_brief.phtml ?>

<div class="article brief">
  <ul>
    <li><?php echo $this->partial('article/url/view.phtml', array('id' => $this->article->id, 'title' => $this->article->title)) ?></li>
    <li><?php echo $this->escape($this->article->lead) ?></li>
    <li><?php echo $this->partial('article/url/edit.phtml', array('id' => $this->article->id)) ?>, <?php echo $this->translate('Delete') ?>
  </ul>
</div>