<form action="<?php echo ($this->object->getId() != null)?$this->url(array('id' => $this->object->id, 'seo' => $this->object->title), 'article'):$this->url(array(), 'articles'); ?>" method="post" accept-charset="utf-8">

<p>
  <label for="title"><?php echo $this->translate('Title'); ?></label>
  <input type="text" name="title" value="<?php echo $this->object->title; ?>" id="title">
</p>
<p>
  <label for="lead"><?php echo $this->translate('Lead'); ?></label>
  <input type="text" name="lead" value="<?php echo $this->object->lead; ?>" id="lead">
</p>
<p>
  <label for="categoryId"><?php echo $this->translate('Category'); ?></label>
  <select name="categoryId" id="categoryId">
    <?php // $this->partialLoop('categories'); ?>
    <option value="option1">Main</option>
    <option value="option2">Cars</option>    
  </select>
</p>  
<p>
  <?php echo $this->FormLabel('body', $this->translate('Article')); ?><br />
  <?php echo $this->FormTextarea('body', $this->object->body); ?>
</p>
<p>
  <label for="author"><?php echo $this->translate('Author'); ?></label>
  <input type="text" name="author" value="<?php echo $this->object->author; ?>" id="author">
</p>
  <p>
    <input type="submit" value="<?php echo $this->translate('Create'); ?> &rarr;">
  </p>
  <input type="hidden" name="id" value="<?php echo $this->object->id; ?>" id="id">
</form>