<!-- <form action="/" method="get" accept-charset="utf-8">
  <label for="password">Password</label>
  <input type="text" name="password" value="" id="password">
  <input type="button" value="Create Trip" />
  <p><input type="submit" value="Continue &rarr;"></p>
</form>


<form id="form" action=";">
  <textarea cols="50" rows="10"></textarea>
  <input type="submit" value="LatteCMS" />
  <select name="country" id="country"  onchange="" size="1">
    <option value="option1">option1</option>
    <option value="option2">option2</option>
    
  </select>
</form> -->

<img src="s/cat.gif" />
